### ISSUE TITLE
Custom cemetery assets support

### ISSUE THREAD

**Issue by SquareBeard** [seanke/BetterCemeteryAI#1]
https://github.com/seanke/BetterCemeteryAI/blob/377e30417c40ccf3910eda7b1646bbc10e07d387/BetterCemeteryAI/NewCemetaryAI.cs#L171

Maybe you could use 2/3 of the cemetery capacity instead of a hard limit of 2000. To make the mod work better with custom cemetery assets.

**Comment by seanke** [comment]
Will do! I also have a change for how it works out what is a cemetery so that it is more reliable with custom cemeteries. Thanks for raising the issue!
